services:
  app:
    build: .
    container_name: crud_node_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: crud_db
    depends_on:
      - postgres_db
    volumes:
      - .:/app
      - /app/node_modules


  postgres_db:
    image: postgres:16
    container_name: crud_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: